# Bienvenido a la configuración de Marina Gaming.
# Cada línea que empieza con '#' es un comentario y es ignorada.

# --- Información Básica del Sitio ---
title: "Marina Gaming Oficial"
description: >-
  Marina Gaming es la comunidad definitiva para jugadores de habla hispana. 
  Únete a nuestra flota en Discord para partidas de GTA Online, FENIX-RolePlay, 
  Halo y sim-racing. Disfruta de nuestra transmisión en vivo 24/7 por MAR TV, 
  apoyo a creadores de contenido y eventos exclusivos.
  
# --- Detalles Técnicos y URL ---
# Séparalo así para que Jekyll y GitHub Pages construyan bien los enlaces
url: "https://manuelheraz.github.io" 
baseurl: "/MarinaGaming"

# Idioma y Región (Crucial para que Google México/Latam te recomiende)
locale: "es-MX"

# Imagen que aparecerá al compartir el link en Discord, WhatsApp, Twitter, etc.
# Sustituye por el link directo a tu logo en alta calidad
image: "https://lh3.google.com/u/2/d/1Y2FY8HucV76hUs6HvRnuhPK8xUpRbQ6Z=w3000-h6501-iv1?auditContext=forDisplay"
logo: "https://lh3.google.com/u/2/d/1Y2FY8HucV76hUs6HvRnuhPK8xUpRbQ6Z=w3000-h6501-iv1?auditContext=forDisplay"

# --- Plugins ---
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# --- Redes Sociales Oficiales ---
author: "Marina Gaming"
twitter:
  username: "JoelHeaz" 
  card: "summary_large_image"

social:
  name: "Marina Gaming"
  links:
    - https://www.youtube.com/@joelheaz
    - https://www.facebook.com/MarinaGamingOfficial
    - https://www.tiktok.com/@joelheaz
    - https://x.com/JoelHeaz
    - https://www.instagram.com/Joel_Heaz
    - https://medium.com/@JoelHeaz
    - https://www.linkedin.com/company/marina-gaming

# --- Configuración de Jekyll (Avanzado) ---
markdown: kramdown